CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    username VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    company_name VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    key_hash VARCHAR(255),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id BIGINT,
    img_url VARCHAR(255),
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id) REFERENCES category (id)
);

CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    codigo_russo INTEGER NOT NULL,
    codigo_mali INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    restricoes_de_uso TEXT,
    recomendacoes_de_uso TEXT,
    observacoes_especiais TEXT,
    observacoes_internas TEXT,
    ip INTEGER NOT NULL,
    amper INTEGER NOT NULL,
    watts INTEGER NOT NULL,
    gtin BIGINT NOT NULL,
    volt INTEGER NOT NULL,
    img_url VARCHAR(255),
    img_public_id VARCHAR(255),
    price DOUBLE PRECISION,
    icon_url VARCHAR(255),
    icon_public_id VARCHAR(255),
    temperatura_de_cor VARCHAR(255),
    leds_por_metro INTEGER NOT NULL,
    tipo_led VARCHAR(255),
    fluxo_luminoso VARCHAR(255),
    indice_de_reproducao_de_cor VARCHAR(255),
    quantide_por_rolo INTEGER NOT NULL,
    sessao_de_corte INTEGER NOT NULL,
    espessura INTEGER NOT NULL,
    blindada BOOLEAN NOT NULL,
    dimensao VARCHAR(255),
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL
);

CREATE TABLE product_category (
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_category_product
        FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT fk_product_category_category
        FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE product_gallery_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255),
    public_id VARCHAR(255),
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_product_gallery_image_product
        FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_date DATE NOT NULL,
    lot VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_orders_company
        FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE TABLE order_products (
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order_products_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_products_product
        FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE print_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    usage_context VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    template_json TEXT NOT NULL,
    width_mm DOUBLE PRECISION,
    height_mm DOUBLE PRECISION,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE wood_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    img_category_url VARCHAR(255),
    parent_id BIGINT,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_wood_category_parent
        FOREIGN KEY (parent_id) REFERENCES wood_category (id)
);

CREATE TABLE wood_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    img_url VARCHAR(255),
    img_public_id VARCHAR(255),
    caixa VARCHAR(255),
    wood_type VARCHAR(255),
    finish VARCHAR(255),
    thickness_mm DOUBLE PRECISION,
    width_mm DOUBLE PRECISION,
    height_mm DOUBLE PRECISION,
    length_mm DOUBLE PRECISION,
    weight_kg DOUBLE PRECISION,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE wood_product_category (
    wood_product_id BIGINT NOT NULL,
    wood_category_id BIGINT NOT NULL,
    PRIMARY KEY (wood_product_id, wood_category_id),
    CONSTRAINT fk_wood_product_category_product
        FOREIGN KEY (wood_product_id) REFERENCES wood_product (id),
    CONSTRAINT fk_wood_product_category_category
        FOREIGN KEY (wood_category_id) REFERENCES wood_category (id)
);

CREATE TABLE wood_product_variation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wood_product_id BIGINT NOT NULL,
    description TEXT,
    color VARCHAR(255),
    sku BIGINT,
    ean BIGINT,
    variation_size VARCHAR(255),
    price DOUBLE PRECISION,
    label_image_url VARCHAR(255),
    label_image_public_id VARCHAR(255),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_wood_product_variation_product
        FOREIGN KEY (wood_product_id) REFERENCES wood_product (id)
);

CREATE TABLE wood_variation_images (
    wood_variation_id BIGINT NOT NULL,
    image_url VARCHAR(255),
    CONSTRAINT fk_wood_variation_images_variation
        FOREIGN KEY (wood_variation_id) REFERENCES wood_product_variation (id)
);
